### ISSUE TITLE
Re: Range format NOT using prettier

### ISSUE THREAD

**Issue by ckuchimanchi** [neoclide/coc-prettier#1]
Hello,

Thanks for the plugin. It's good!

I've coc.nvim installed and this extension (coc-prettier) along with other extensions like eslint and json.

With these settings below, whenever I try and save the file in vim (:write), I get a clear message that prettier formatted the file and it works as expected. 

```
{
  "prettier.eslintIntegration": true,
  "coc.preferences.formatOnSaveFiletypes": ["javascript", "css", "json"],
  "coc.preferences.formatOnType": false
}

```
However, when I do "range formatting" as suggested in coc-prettier readme, it doesn't seem to be using prettier and formats it in a very different way. It shows the command executed to be

`:call CocAction('formatSelected', visualmode())`

Here are my mappings (as per coc-prettier readme)

```
vmap <leader>f  <Plug>(coc-format-selected)
nmap <leader>f  <Plug>(coc-format-selected)

```
formatOnSaveFileTypes option seems to be of coc.nvim (not prettier) and yet it's handled by prettier when I save the file. So I expected the format selections also to be overridden by prettier to be consistent? It doesn't seem to be the case. Am I missing something?

Below command works fine as when I save/write the file. It's calling prettier directly and works as expected.

`:call CocAction('runCommand', 'prettier.formatFile')`

I just find the range format getting it wrong - inconsistent with my prettier config settings. Is that expected? 

And btw, what's the default formatting style for coc.nvim. What does it use as it's base for formatting (if prettier isn't installed or isn't being triggered like in above case)

Thanks in advance.

Please let me know if anything is unclear.

**Comment by chemzqm** [comment]
> what's the default formatting style for coc.nvim.

Coc.nvim eval options including `tabstop` and `expandtab` from vim for basic format options, other format settings are loaded by language server,  checkout https://github.com/neoclide/coc-prettier#prettiers-settings

> So I expected the format selections also to be overridden by prettier to be consistent? It doesn't seem to be the case. Am I missing something?

It should be, but prettier itself only support range format for limited filetypes https://github.com/neoclide/coc-prettier#remap-keys-for-range-format-in-your-initvim-or-vimrc.
What is the filetype of your file?

**Comment by chemzqm** [comment]
`coc-tsserver` also contribute format providers, and it have higher priority.

**Comment by chemzqm** [comment]
The json language server registered format range provider but not format document provider, so you have that behavior.

**Comment by chemzqm** [comment]
You can get the output  from coc-prettier by use command `:CocCommand workspace.showOutput prettier`, it's improved.

**Comment by ckuchimanchi** [comment]
Hi @chemzqm 

Thanks again for your help. 

So, below is my understanding, can you confirm if this is correct?

There are three formatting sources in the following priority order

1. language server (either json or js based on file type)
2. coc-prettier
3. coc-nvim (some defaults based on file type and vim settings)

`<Plug>(coc-format-selected)`  picks up one of the above based on it being present for range formatting. 

And,

`"coc.preferences.formatOnSaveFiletypes": ["javascript", "css", "json"]`

formatOnSaveFileTypes would work like above, just that it works on full files always?

So, based on this, if tssserver supports full document formatting and always takes more priority, coc-prettier would never get called for javascript files - unless I explicity execute the below command, and also disable formatOnSave option? Is my understanding right?

`:call CocAction('runCommand', 'prettier.formatFile')`

If so, I find that a bit disappointing as the whole reason for using prettier is for it to take care of this formatting automatically whenever I save the file. Is there a way around this? (apart from perhaps writing an autocommand for Buffwrite?)

Thanks

**Comment by chemzqm** [comment]
> coc-nvim (some defaults based on file type and vim settings)

There's no default fomatter from coc itself, language server have higher priority since it could gives you better control (most likely).

>  Is there a way around this? (apart from perhaps writing an autocommand for Buffwrite?)

Exclude `javascript` from `"coc.preferences.formatOnSaveFiletypes"` and add a vim autocmd:

```
  autocmd BufWritePre *.js CocCommand prettier.formatFile
```
to your `.vimrc`.

Lots of format options are provided by coc-tsserer https://github.com/neoclide/coc-tsserver/blob/master/package.json#L341 and it has support for format on type feature, so consider use tsserver for format javascript file.

**Comment by ckuchimanchi** [comment]
> You can get the output from coc-prettier by use command `:CocCommand workspace.showOutput prettier`, it's improved.

I tried this on json and js files, and unfortunately couldn't find anything logged on the window (it was empty). I tried both before and after running the command.

**Comment by chemzqm** [comment]
> unfortunately couldn't find anything logged on the window

Try update extensions by command `:CocUpdate`, old version only log on error.

**Comment by ckuchimanchi** [comment]
Thanks @chemzqm . I'm still not able to see output log of prettier (even after updating the extension), but closing this issue for now. Thanks again for all the help.

**Comment by nicobao** [comment]
> > what's the default formatting style for coc.nvim.
> 
> Coc.nvim eval options including `tabstop` and `expandtab` from vim for basic format options, other format settings are loaded by language server, checkout https://github.com/neoclide/coc-prettier#prettiers-settings
> 
> > So I expected the format selections also to be overridden by prettier to be consistent? It doesn't seem to be the case. Am I missing something?
> 
> It should be, but prettier itself only support range format for limited filetypes https://github.com/neoclide/coc-prettier#remap-keys-for-range-format-in-your-initvim-or-vimrc.
> What is the filetype of your file?

Hello! Sorry for reviving an old thread. However, I'd like to disable sending `options` to the language server with the `rangeFormatting` message depending on my own user's settings (`expandtab` and `tabstop`). Often, my settings are wrong for the team, but the formatting file used by the whole team is correct, and I don't want to change my vim settings because I use them for other projects.
How is that possible?

**Comment by chemzqm** [comment]
Use local vimrc or write autocmd.

**Comment by nicobao** [comment]
Hmmm... I'll have the same problem for many environment and languages, that's what I wanted to avoid. Is there a g:coc_something that I can set to false to avoid sending the options? If not, can I send a PR with this option, would you accept it? (default to current behaviour)

**Comment by nicobao** [comment]
Besides, I don't want to alter the team's agreed formatting settings file in any ways with my own vim settings.
Your suggestion and mine are not incompatible.
Yes I can make project-specific configuration to adjust to each team's settings.
But when clicking on "format" my expectation is that the single source of truth for the team, the external setting file, will be applied to my file, independently on my own settings. It's also a way to make sure my own vim settings are not incompatible...

**Comment by chemzqm** [comment]
> can I send a PR with this parameter, would you accept it? (default to current behaviour)

No, because it's not necessary, you should fix `'shiftwidth'` and `'tabstop'` option for your buffer which also affect your normal edit experience.

**Comment by nicobao** [comment]
I was using vim-polyglot which embeds https://github.com/tpope/vim-sleuth
It's changing shiftwidth and expandtab depending on current buffer. 
Obviously when you edit a wrongly-indented file, this makes wrong values. As it often happens in projects, team's formatting settings change, and then you need to format old files, which wrong tabs values. These values should not be sent via options.
This PR is really necessary... I don't understand why your personal settings should change the way you format files. Formatting settings file are here for a reason: a single source of truth across editors... Not having this option is almost like removing the whole point of third-party formatter in the first place.
