### ISSUE TITLE
prettifying .scss has ended up with an error.

### ISSUE THREAD

**Issue by emeentag** [neoclide/coc-prettier#10]
Hi while i am trying to format my .scss files i am getting this error below when i run `:CocCommand prettier.open-output` command:

```.config/coc/extensions/node_modules/prettier-stylelint/node_modules/stylelint/lib/getConfigForFile.js:46:15```

When i checked the file as far as i see, it needs a config file for this action but the file could not found.

Thx...

**Comment by chemzqm** [comment]
read doc of stylelint
