### ISSUE TITLE
Version 1.1.19 causes prettier to format without bracket spacing

### ISSUE THREAD

**Issue by kimpers** [neoclide/coc-prettier#100]
Hi,

When upgrading to `1.1.19` I noticed that the default value for `bracketSpacing` is no longer correct. It automatically formats  `{ hello: 'world' }` to `{hello: 'world'}`, even though the prettier default value should be spacing enabled.

Manually overriding `prettier.bracketSpacing` in my coc config also does not have any effect. Downgrading to `1.1.18` resolved the issue.

**Comment by yale** [comment]
Same issue here. @kimpers how did you downgrade?

**Comment by kimpers** [comment]
@yale you can install version `1.1.18` with `:CocInstall coc-prettier@1.1.18`

**Comment by yale** [comment]
thank you @kimpers!

**Comment by chemzqm** [comment]
No idea, v1.1.9 only improved the option for get supported languageIds.

**Comment by jose-elias-alvarez** [comment]
I'm having the same issue with bracket spacing, and Prettier itself occasionally breaks and won't format the document. In `:messages`, I see the following:

`[coc.nvim] languageserver will save operation timeout after 0.5s`

Reverting back to 1.1.18 fixes this, too.

**Comment by piouPiouM** [comment]
> No idea, v1.1.9 only improved the option for get supported languageIds.

@chemzqm In fact, `coc-prettier@v1.1.9` is based on a [breaking change of the API](https://github.com/prettier/prettier/commit/cf3d9f0b8074306fde479c19689deffe38142e4f) which forces to upgrade the local instance of Prettier to 2.0.0

**Comment by mfcarneiro** [comment]
Yea, same where.
Got some problems with v1.1.19, just did a downgrade to v1.1.18 and all back to work normally.
