### ISSUE TITLE
Code deleted on auto-save format by prettier

### ISSUE THREAD

**Issue by himat** [neoclide/coc-prettier#102]
I had written a function and then saved inside vim `:w`, and then coc-prettier ran on save, but it actually deleted the body of my function.

This is in a `.ts` file:
```
 export async function x(y: number) {
     return await fetch(
         `${backendUrl()}/fds`,
         {
             method: "get",
             mode: "cors",
         }
     );
 }
```
on save, this turned into

```
 export async function x(y: number) {}
```

I'm unable to replicate this but the fact that this happened makes it dangerous to use the auto formatting if it deletes code and I don't catch it.

**Comment by chemzqm** [comment]
Please try minimal vimrc.
