### ISSUE TITLE
fallback to normal prettier format when no eslint configuration found

### ISSUE THREAD

**Issue by GopherJ** [neoclide/coc-prettier#104]
currently coc-prettier keeps giving erros while:

```
 "prettier.eslintIntegration": true,
```

and `.eslintrc.js` , `.eslintrc.json` not found

It'll be good to ignore ` "prettier.eslintIntegration": true,` if  eslint config not found

**Comment by GopherJ** [comment]
so that we don't need to see again and again the following error:


![image](https://user-images.githubusercontent.com/33961674/102699338-20c62d00-4244-11eb-844c-7f4383e144bc.png)

**Comment by chemzqm** [comment]
We don't have any support for eslint configuration detect, you can create coc extension yourself.

**Comment by GopherJ** [comment]
@chemzqm don't be angry about such small thing! I create issue because I want to improve it...

after checking the code it looks like more on: https://github.com/prettier/prettier-eslint side
