### ISSUE TITLE
coc-prettier conflicts with Jinja in HTML element attributes

### ISSUE THREAD

**Issue by BrianZhang1** [neoclide/coc-prettier#106]
Below, you can find two photos, one before the prettier autoformat and one after the formatting. Watch how the highlighted line in the photos changes.

Before: https://imgur.com/a/q8EmOAn
After: https://imgur.com/a/AhLguUh

As you can see, prettier automatically adds a pair of "" around the {{ in the value of the first input element in the form, but doesn't effect the non-attribute {{}} pairs. The problem is, by changing `{{` to `"{{"`, it breaks my code. It is pretty annoying to have to save with `:noa w`, and lose prettier formatting in my file on top of that. Maybe a work around to this should be added.

**Comment by chemzqm** [comment]
Should be problem of your language server, checkout https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel

**Comment by BrianZhang1** [comment]
> Should be problem of your language server, checkout https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel

I checked out the output channel, but prettier never specified the language server. I assume the language server that is being used is the coc-html plugin, since that's the only lsp that appears in the list after running `:CocCommandworkspace.showOutput`. Should I open an issue there instead?
I also couldn't find any settings in coc-html that allowed me to stop the language server from auto enclosing attributes in "".

**Comment by chemzqm** [comment]
Try configure `prettier.enable`, `prettier.disableLanguages` and `prettier.formatterPriority`
