### ISSUE TITLE
Prettier ESLint not approved

### ISSUE THREAD

**Issue by jrock2004** [neoclide/coc-prettier#107]
Not sure if this is coming from coc prettier but not sure how I can approve

![image](https://user-images.githubusercontent.com/655716/104204642-7fbe3280-53fb-11eb-899b-fb421e9c7b90.png)

**Comment by dunnock** [comment]
Have the same issue 
```
vim version: NVIM v0.4.4
node version: v14.15.1
coc.nvim version: 0.0.80-7c70fbf971
```

**Comment by dunnock** [comment]
FWIW after reading diagnostic message it says how to approve:
```
Use :CocCommand eslint.showOutputChannel to open the approval dialog
```

**Comment by jrock2004** [comment]
That worked. Thank you

**Comment by saurabhmehta1601** [comment]
Is there some way to not do it manually and just let coc follow the eslint config in the project inside elintrc if exists

**Comment by chemzqm** [comment]
Configure `eslint.probe` if you're using coc-eslint.
