### ISSUE TITLE
coc-prettier ignores 'overrides' section of .prettier.rc for supported file types

### ISSUE THREAD

**Issue by rmzg** [neoclide/coc-prettier#108]
If you have a file 'foo.hbs' and run `:CocCommand prettier.formatFile` you get `[coc.nvim] html.handlebars not supported by prettier` even if you've used:
```
  "overrides": [
    {
      "files": "*.hbs",
      "options": { "parser": "html" }
    }
  ]
```
in your local .prettier.rc file

**Comment by rmzg** [comment]
Note that prettier actually has a function specifically for this: `prettier.getFileInfo(filePath [, options])`

https://prettier.io/docs/en/api.html#prettiergetfileinfofilepath--options

**Comment by ayush-mandowara-bst** [comment]
Is this issue resolved?

**Comment by rmzg** [comment]
Not as far as I can tell.

**Comment by chemzqm** [comment]
`:h g:coc_filetype_map`
