### ISSUE TITLE
Required trailing comma is deleted in .tsx

### ISSUE THREAD

**Issue by navel3** [neoclide/coc-prettier#109]
Generic arrow function requires trailing comma for type parameters in `.tsx`, but coc-prettier deletes it.

Before format.
```tsx
const f = <T,>(a: T) => a
```

After format.
```tsx
const f = <T>(a: T) => a  // Syntax error
```

Prettier had the same issue, but it was fixed in [this PR](https://github.com/prettier/prettier/pull/6115).

I think coc-prettier probably format the file as `.ts` instead of `.tsx`.

**Comment by kovetskiy** [comment]
Should be fixed by #112
