### ISSUE TITLE
[help] Silent failure

### ISSUE THREAD

**Issue by maricn** [neoclide/coc-prettier#110]
### What doesn't work
* `:call CocAction('format')`
* `:CocCommand prettier.formatFile`
* `:Prettier`

The commands report success, but the file doesn't change. Especially with `:call CocAction('format')` I get the response `[coc.nvim] Formatted by prettier`, while with other two commands it just finishes without reporting anything in the output. Ofc, format on save doesn't work.

All of those worked completely fine until a few days ago. I don't know what changed, I did run arch packages update and update of vim plugins and of coc extensions but i've also tried reverting them without fixing the problem.

### I tried
* reverting my dotfiles to a point where it surely worked ([my .vimrc](https://github.com/maricn/dotfiles/blob/master/.vimrc))
* reverting the project in question to a point when it worked
* trying it out on a different typescript project (the two use node versions `v10.20.1` and `v12.14.1`)
* reinstalling older version of coc-prettier (tried 1.1.18, 1.1.19, 1.1.20)
* updating `prettier` dependency to the latest version

### What works well
* Interesting thing is that in that project I have this script:
```json
"format": "prettier --write \"src/**/*.ts\""
```
Which works just fine.
* Also if I run `./node_modules/prettier/bin-prettier.js src/main.ts` from the project's root, the output is properly reformatted file.
* Running it on a pure javascript file works well (in any project)

### Context (files)
`:CocConfig` (only global, no local):
```json
{
  "prettier.tslintIntegration": true,
  "coc.preferences.formatOnSaveFiletypes": [
    "css",
    "javascript",
    "typescript",
    "json",
    "jsonc"
  ],
  "coc.preferences.colorSupport": false,
  "diagnostic.hintSign": ">>",
  "diagnostic.infoSign": "ℹ️",
  "diagnostic.warningSign": "⚠️",
  "diagnostic.errorSign": "💣",
  "diagnostic.enableHighlightLineNumber": true,
  "diagnostic-languageserver.filetypes": {
    "vim": "vint",
    "email": "languagetool",
    "markdown": ["write-good", "markdownlint"],
    "sh": "shellcheck"
  },
  "typescript.preferences.importModuleSpecifier": "relative",
  "markdownlint.config": {
    "line-length": false,
    "MD022": false,
    "MD032": false,
    "MD033": false, // inline HTML shouldn't be forbidden (<a name="asdf"></a>...[goto](#asdf))
    "MD034": false,
    "MD025": { "front_matter_title": "" }
  },
  "languageserver": {
    "ccls": {
      "command": "ccls",
      "filetypes": ["c", "cpp", "cuda", "objc", "objcpp"],
      "rootPatterns": [".ccls-root", "compile_commands.json"],
      "initializationOptions": {
        "cache": {
          "directory": ".ccls-cache"
        },
        "client": {
          "snippetSupport": true
        }
      }
    }
  },
  "explorer.icon.enableNerdfont": true
}
```

`.config/coc/extensions/package.json`:
```json
{
  "dependencies": {
    "coc-db": ">=0.0.43",
    "coc-emoji": ">=1.2.3",
    "coc-explorer": ">=0.9.1",
    "coc-highlight": ">=1.2.6",
    "coc-jest": ">=1.1.1",
    "coc-json": ">=1.3.2",
    "coc-markdownlint": ">=1.7.0",
    "coc-prettier": ">=1.1.18",
    "coc-python": ">=1.2.13",
    "coc-sql": ">=0.4.0",
    "coc-syntax": ">=1.2.4",
    "coc-tsserver": ">=1.6.0",
    "coc-word": ">=1.2.2"
  }
}
```

`.prettierrc`:
```json
{
  "useTabs": false,
  "singleQuote": true,
  "trailingComma": "all",
  "tabWidth": 2,
  "printWidth": 120
}
```

`tslint.json`:
```json
{
  "defaultSeverity": "error",
  "extends": ["tslint:recommended", "tslint-config-prettier"],
  "jsRules": {
    "no-unused-expression": true
  },
  "rules": {
    "arrow-parens": false,
    "array-type": false,
    "curly": [true, "ignore-same-line"],
    "eofline": true,
    "indent": [true, "spaces", 2],
    "interface-name": false,
    "max-classes-per-file": false,
    "max-line-length": [true, 120],
    "member-access": false,
    "member-ordering": [
      true,
      {
        "order": [
          "public-static-field",
          "public-static-method",
          "protected-static-field",
          "protected-static-method",
          "private-static-field",
          "private-static-method",
          "public-instance-field",
          "protected-instance-field",
          "private-instance-field",
          "public-constructor",
          "protected-constructor",
          "private-constructor",
          "public-instance-method",
          "protected-instance-method",
          "private-instance-method"
        ]
      }
    ],
    "no-empty": false,
    "no-empty-interface": false,
    "no-unused-expression": true,
    "object-literal-sort-keys": false,
    "one-line": true,
    "one-variable-per-declaration": true,
    "ordered-imports": true,
    "quotemark": [true, "single", "avoid-escape"],
    "variable-name": [
      true,
      "ban-keywords",
      "check-format",
      "allow-snake-case",
      "allow-pascal-case",
      "allow-leading-underscore"
    ]
  },
  "rulesDirectory": []
}
```

**Comment by dlee** [comment]
I'm running into the same issue, except it only happens on a specific file. Other files get properly formatted.

**Comment by indeedwatson** [comment]
> I'm running into the same issue, except it only happens on a specific file. Other files get properly formatted.

Same here, with an html file

**Comment by kozer** [comment]
Just out of curiosity, as I had a similar problem. Does add `prettier-tslint` to your project solve the issue?

**Comment by chemzqm** [comment]
It could be using bundled prettier from coc-prettier before.

**Comment by chemzqm** [comment]
It could be using bundled prettier from coc-prettier before.

**Comment by kozer** [comment]
@maricn This is what puzzles me also, as the bundled prettier-tslint is in there (in coc-prettier's node modules/.bin)

**Comment by chemzqm** [comment]
Local prettier is used when possible by default, so when you don't have global prettier, local prettier is used.

**Comment by kozer** [comment]
@chemzqm I think that this is not the same functionality as vs code. In vs code I didn't have to install prettier-tslint in order to make it work with typescript files.
Maybe this is a bug?

**Comment by chemzqm** [comment]
I see, seems API used by prettier get changed.

**Comment by chemzqm** [comment]
Works as expected for me, don't know how to reproduce.

**Comment by maricn** [comment]
@chemzqm Without going into the internals of this package, maybe this line from my original post is helpful:

>  Especially with `:call CocAction('format')` I get the response `[coc.nvim] Formatted by prettier`, while with other two commands it just finishes without reporting anything in the output. Ofc, format on save doesn't work.

So, maybe the way the plugin detects failure of the external command is flawed? It reports success, but actually nothing happened. Is the fallback to plugin's prettier working in case there's an error with the local one (if it's how it works anyways)?

**Comment by chemzqm** [comment]
Please checkout output from coc-prettier https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel

**Comment by maricn** [comment]
> Please checkout output from coc-prettier [neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel](https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel)

```javascript
[Error - 6/18/2021, 6:07:32 PM:] Failed to load prettier-tslint from /home/nikola/.dotfiles/.config/coc/extensions/node_modules/coc-prettier


[Error - 6/18/2021, 6:07:32 PM:] Cannot read property 'format' of null


[Trace - 6/18/2021, 6:07:32 PM:] Formatted file: file:///home/nikola/Workspace/ProjectXXX/src/PackageYYY/FileZZZ.ts


[Trace - 6/18/2021, 6:07:32 PM:] Prettier format edits: [
  {
    "range": {
      "start": {
        "character": 0,
        "line": 0
      },
      "end": {
        "character": 0,
        "line": 54
      }
    },
    "newText": "REDACTED"
  }
]

```

there's some symlinks on that path, but this is what's there:
```bash
$> ls -lah /home/nikola/.dotfiles/.config/coc/extensions/node_modules/coc-prettier
.rw-r--r-- nikola nikola 116 B  Tue Mar 30 10:30:48 2021  .prettierrc
drwxr-xr-x nikola nikola 4.0 KB Tue Mar 30 10:30:48 2021  .release/
.rw-r--r-- nikola nikola 460 B  Tue Mar 30 10:30:48 2021  CHANGELOG.md
.rw-r--r-- nikola nikola 481 B  Tue Mar 30 10:30:48 2021  esbuild.js
drwxr-xr-x nikola nikola 4.0 KB Tue Mar 30 10:30:48 2021  lib/
drwxr-xr-x nikola nikola  20 KB Tue Mar 30 10:30:48 2021  node_modules/
.rw-r--r-- nikola nikola 233 B  Tue Mar 30 10:30:34 2021  package-json-schema.json
.rw-r--r-- nikola nikola 204 KB Tue Mar 30 10:30:34 2021  package-lock.json
.rw-r--r-- nikola nikola 7.7 KB Tue Mar 30 10:30:34 2021  package.json
.rw-r--r-- nikola nikola 5.9 KB Tue Mar 30 10:30:48 2021  Readme.md
```

Not sure what this line means:
```bash
[Error - 6/18/2021, 6:07:32 PM:] Cannot read property 'format' of null
```

**Comment by chemzqm** [comment]
There should be prettier-tslint inside node_modules folder of coc-prettier

**Comment by maricn** [comment]
> There should be prettier-tslint inside node_modules folder of coc-prettier

I have `prettier-tslint` version `0.4.2` ([latest, from Jan 2019](https://github.com/azz/prettier-tslint/releases/tag/v0.4.2)) inside `coc-prettier` version `1.1.23`.

**Comment by derekstavis** [comment]
I'm using `coc-prettier@1.1.24` and `coc@. I was having a similar problem where files were not being formatted and just a new line was being added to the end of the file. After installing `prettier-tslint` to my project it started working again.

**Comment by dnyaneshwar89** [comment]
Having same problem.
where and how can i add prettier-tslint?

**Comment by chemzqm** [comment]
Make sure check the Prettier output by `:CocCommand workspace.showOutput`
