### ISSUE TITLE
extension uses incorrect version of prettier

### ISSUE THREAD

**Issue by GabrielDuarteM** [neoclide/coc-prettier#12]
I work on a project with other people, and we're currently using an older version of prettier (which is run on changed files on every commit). When I run this plugin, I expected that the local version would be used, but instead, it is using some other version (probably a more recent one, bundled with the plugin). Because of that, every time I commit I have to run again the local version of prettier with `npx prettier --write`, so that it correctly formats according to our project.

With this in mind, two ideas popped up:
1) Always prefer the local version (I think that's more reasonable to expect instead of the bundled one, given that we already have prettier installed on the project). Maybe there could be an option to specify otherwise, but I'm not sure if that's needed...

2) An option to only run prettier if the project has the package installed (it is on the `package.json` devDependencies). Some projects do not use and do not have any intention on installing prettier on it, so its annoying to have to disable the extension every time I want to submit a PR to one of those projects. If there was an option like `forceUsingLocalVersion`, It could be done something like `coc-prettier` simply do nothing, or maybe show a warning when the file is opened (like it is done with eslint)

![image](https://user-images.githubusercontent.com/7675500/60158127-b0765100-97f0-11e9-8e97-748da3a75667.png)

What do you think? 😃

**Comment by chemzqm** [comment]
I'm fine with that, but don't have time for it for now, PR welcome.

**Comment by GabrielDuarteM** [comment]
Sure, I can take a look into that later today and see
