### ISSUE TITLE
Formatting html.erb files

### ISSUE THREAD

**Issue by domi91c** [neoclide/coc-prettier#126]
Curious if it would be possible for this to work with ERB files (Ruby and HTML).

Right now I get the error "format provider not found for current buffer, your language server does not support it". 

There is a [prettier ERB plugin](https://github.com/adamzapasnik/prettier-plugin-erb), but I'm not sure if it's possible to make it work with coc-prettier.

**Comment by chemzqm** [comment]
Install the prettier plugin with your local prettier and make coc-prettier use your local prettier and make sure the filetype match required languageIs by that ERB plugin.
