### ISSUE TITLE
Add support for 'markdown.mdx' filetype

### ISSUE THREAD

**Issue by roginfarrer** [neoclide/coc-prettier#127]
CocCommand works with the `mdx` filetype, but it doesn't work with the compound filetype `markdown.mdx`. The only plugin that supports highlighting for mdx files, [vim-mdx-js](https://github.com/jxnblk/vim-mdx-js/), uses the compound filetype in order to tie in normal syntax highlighting for markdown.

One workaround is to temporarily set the ft to `mdx`, format, then return, but that's not ideal.

**Comment by chemzqm** [comment]
`:h g:coc_filetype_map`

**Comment by roginfarrer** [comment]
Ah, didn't know about this, thank you!

For those who want to copy/paste the solution:

```vim
" vim
let g:coc_filetype_map = { 'markdown.mdx': 'mdx' }
```

Or

```lua
-- lua
vim.g.coc_filetype_map = {
  ["markdown.mdx"] = "mdx"
}
```
