### ISSUE TITLE
semver.simplifyRange is not a function

### ISSUE THREAD

**Issue by ik5** [neoclide/coc-prettier#128]
When trying to install the package the package using `CocInstall` I get the Following error message:

`semver.simplifyRange is not a function`.

Attaching the npm log file.

[2021-06-04T17_14_59_476Z-debug.log](https://github.com/neoclide/coc-prettier/files/6600218/2021-06-04T17_14_59_476Z-debug.log)

**Comment by chemzqm** [comment]
Could be issue with your npm, can't help.

**Comment by ik5** [comment]
thank you
