### ISSUE TITLE
No reaction to endOfLine settings

### ISSUE THREAD

**Issue by kaykhancheckpoint** [neoclide/coc-prettier#129]
Hi friends, i am having an issue in vim in which prettier asks me to delete the extra/empty line at the end of a file, however vscode correctly enforces the need for an empty line at the end of a file.

To be clear im on linux and i do prefer my files to have an empty ending line at the bottom of the file.

**coc-settings.json**

```
{ 
    "coc.preferences.formatOnSaveFiletypes": ["javascript", "typescript", "python"],
    "prettier.requireConfig": true
}
```

.prettierrc

```
{
    "semi": true,
    "tabWidth": 4,
    "endOfLine": "auto"
}
```

.eslintrc.json

```
{
    "env": {
        "browser": true,
        "es2021": true,
        "node": true
    },
    "extends": [
        "eslint:recommended",
        "plugin:@typescript-eslint/recommended",
        "prettier",
        "plugin:prettier/recommended"
    ],
    "parser": "@typescript-eslint/parser",
    "parserOptions": {
        "ecmaVersion": 12,
        "sourceType": "module"
    },
    "plugins": [
        "@typescript-eslint"
    ],
    "rules": {
        "@typescript-eslint/no-explicit-any": "off",
        "@typescript-eslint/explicit-module-boundary-types": "off",
        "@typescript-eslint/no-unused-vars": "off",
        "no-useless-catch": "off",
        "linebreak-style": [
            "error",
            "unix"
        ],
        "quotes": [
            "error",
            "double"
        ],
        "semi": [
            "error",
            "always"
        ],
        "prettier/prettier": [
            "error",
            { "endOfLine": "auto" }
        ]
    }
}

```

**vim**

![image](https://user-images.githubusercontent.com/65535942/120845768-251fa180-c569-11eb-8a28-5c15c7c7106b.png)

**vscode**

![image](https://user-images.githubusercontent.com/65535942/120845821-3a94cb80-c569-11eb-9386-0b62b4d63d90.png)

vscode has it correct in this case, what is happening with vim?

**Comment by chemzqm** [comment]
Unlike vscode, vim doesn't show the last end of line, when you have extra empty line at the end, it means you have `\n\n` at the end of buffer.
