### ISSUE TITLE
Prettier failed on tsx files

### ISSUE THREAD

**Issue by kozer** [neoclide/coc-prettier#130]
Having `typescriptreact` and `typescript` on my formatfilesOnSave make prettier failed with the following.
```
[Error - 6/17/2021, 10:05:21 PM:] Failed to load prettier-tslint from <my-home-path>/node_modules/coc-prettier


[Error - 6/17/2021, 10:05:21 PM:] Cannot read property 'format' of null
```
Notice that I have prettier installed locally in my project.
If I install `prettier-tslint` locally as well everything works as expected.

The local installation of `prettier` doesn't seem to be the issue though as removing it makes the error message still appears. (At first I thought that the local version was creating an issue resolving the bundled prettier)

Also a strange thing is that I have those options in my `coc-config`

```
"prettier.tslintIntegration": "false",
"prettier.eslintIntegration": "false",
"prettier.stylelintIntegration": "false",
```

Seems that it tries to resolve prettier-tslint from my project and not using the bundled one.

Could you provide some help to solve this?

Thanks!

PS: Installed local typescript version: `"typescript": "^4.2.3",`
PS2: Don't think that's relative but I don't have a coc-config json file. I use `let g:coc_user_config` in my vim config to provide coc nvim with my preferred options

**Comment by chemzqm** [comment]
Try `:echo CocAction getConfig('prettier')`

**Comment by kozer** [comment]
If I run this specific command I get `E121: Undefined variable: CocAction`. Is this correct?

**Comment by fannheyward** [comment]
`:echo CocAction('getConfig', 'prettier')`

**Comment by kozer** [comment]
Thanks @fannheyward . Still no clue how this will solve the issue. I get the config back, so what?

**Comment by fannheyward** [comment]
It's `"prettier.tslintIntegration": false`, not `"false"`, type is boolean https://github.com/neoclide/coc-prettier/blob/master/package.json#L47-L49.

**Comment by chemzqm** [comment]
Use https://github.com/neoclide/coc-json for json validation is recommended.
