### ISSUE TITLE
Prisma need support for prettier

### ISSUE THREAD

**Issue by maxmx03** [neoclide/coc-prettier#133]
Hello, i tried to format prisma file with this plugin: [plugin](https://github.com/umidbekk/prettier-plugin-prisma#readme) but didnt work.
coc-prettier doesnt support plugins?

![Captura de tela de 2021-08-21 22-52-10](https://user-images.githubusercontent.com/50273941/130339311-adb1c90e-a35e-49ad-872d-b6f25b2aba52.png)

I'm formatting this way at the moment: `autocmd InsertLeave *.prisma :!npx prisma format`

**Comment by SOLID-arity** [comment]
This didn't work for me unfortunately. Any idea how to get it to work?

**Comment by chemzqm** [comment]
You have to make used the prettier used by coc-prettier installed with your plugin, use command `:CocCommand prettier.openOutput`
