### ISSUE TITLE
Code alternating between formatted and unformatted on subsequent writes

### ISSUE THREAD

**Issue by scallaway** [neoclide/coc-prettier#137]
This is an interesting one that I've been observing for as long as I can remember, and was the reason for me taking time away for `coc` to try alternatives, but I'm determined to get to the bottom of it.

My neovim (v0.5.0) is setup with `coc` alongside other plugins (that don't interact with code formatting). Within `coc` I make use of both Prettier and ESLint through the `coc-prettier` and `coc-eslint` respectively.

When I write to a file in neovim, for the first time I get formatting correctly. However, if I then don't make any changes and proceed to write again, I observe that the formatting gets removed and the code looks like a mess.

I have seen worse instances where it seemingly breaks code completely, through formatting alone. Which is a real problem when in the flow of working.

I have also observed instances where adding a new line to an existing file that is formatted correctly (the new line isn't), and then calling write, the new file gets formatted correctly but the rest of the file gets unformatted. This then alternates (like above) on subsequent writes. I have to close the file and open it again to get correct formatting.

Happy to go through some troubleshooting to get to the bottom of this, since this is the premier Prettier plugin for coc, and the ecosystem itself is too good to give up!

Thanks in advance

**Comment by chemzqm** [comment]
Seems duplicate issue of #134

**Comment by bobwhitelock** [comment]
I believe this is also resolved now https://github.com/neoclide/coc-prettier/issues/134 is fixed
