### ISSUE TITLE
Bump prettier's version number, features are missing

### ISSUE THREAD

**Issue by 205g0** [neoclide/coc-prettier#138]
coc-prettier uses prettier 2.2.x, prettier is now at 2.4.1 with some new important features.

**Comment by laem** [comment]
Prettier 2.5 has even better features : Typescript 4.5 and MDX 2

https://prettier.io/blog/2021/11/25/2.5.0.html

**Comment by chemzqm** [comment]
Set `"prettier.onlyUseLocalVersion": true` to use local prettier only.

**Comment by chemzqm** [comment]
It's not recommended to use bundled prettier, checkout https://github.com/neoclide/coc-prettier/blob/master/Readme.md#prettier-resolution
