### ISSUE TITLE
How to use eslint configuration?

### ISSUE THREAD

**Issue by abidibo** [neoclide/coc-prettier#147]
After a fresh install I can see that the `prettier.eslintIntegration` option is gone. So I've a difference between how mi code is formatted and how my code is linted.

Is there a way to make prettier work using the eslint rules again?

Thanks

**Comment by chemzqm** [comment]
You have to install prettier plugin with prettier used by coc-prettier and configure it https://github.com/neoclide/coc-prettier#plugins
