### ISSUE TITLE
import_coc6.window.onDidChangeActiveTextE ditor is not a function

### ISSUE THREAD

**Issue by peterbabic** [neoclide/coc-prettier#150]
Trying a workaround for the issue described in https://github.com/marlonfan/coc-phpls/issues/104#issuecomment-1120253793 with the coc-prettier at the latest version I am getting a message:

`[coc.nvim] Error on activate extension coc-prettier: import_coc6.window.onDidChangeActiveTextE
ditor is not a function`

**Comment by chemzqm** [comment]
Please update your coc.nvim
