### ISSUE TITLE
"prettier.tabWidth": 4   This setting does not work in c/cpp files ,is it always use google code style?

### ISSUE THREAD

**Issue by yong580** [neoclide/coc-prettier#160]
formatting result still keep tabWidth= 2
#include <errno.h>
#include <pthread.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>

int hello() {
  printf("hello world\n");
  return 0;
}
int main() {
  int i = 0;
  int b = 5;
  hello();
}

**Comment by zwjaaa** [comment]
same question.

**Comment by zwjaaa** [comment]
OK, i found the solution in [this](https://github.com/clangd/coc-clangd/issues/345#issuecomment-910353517).
All we need to do is to create a `.clang-format` in our project or home directory, the content is simple:

`IndentWidth: 4`

**Comment by chemzqm** [comment]
Clangd uses it's own format file.
