### ISSUE TITLE
when using prettier-eslint via prettier.eslintIntegration should be able to pass also the eslintConfig

### ISSUE THREAD

**Issue by zelphir** [neoclide/coc-prettier#17]
Scenario:
```
/myApp
|_someGoCode
|_somePythonCode
|_someJSCode
  |_.eslintrc
  |_.prettierrc
  |_node_modules
```

`coc-settings.json` with `"prettier.eslintIntegration": true`

I usually open neovim from the root to have all the folders available and work on different languages, when I run `:Prettier` on a js/ts file it throws this error:
`[coc.nvim] error: prettier-eslint [ERROR]: eslint fix failed due to an eslint error`, if I open neovim in `myApp/someJSCode` everything works as expected, I guess it's beacuse `prettier-eslint` is not resolving the `node_modules` folder within `someJSCode` this is also confermed running `CocInfo`:

```
## Output channel: prettier


[Error - 7/19/2019, 11:22:25 AM:] Failed to load plugin 'jest' declared in 'CLIOptions'/path/to/myApp/someJSCode/src/pages/index.tsx:: Cannot find module 'eslint-plugin-jest'
Require stack:
- /path/to/myApp/__placeholder__.js <== here should be /path/to/myApp/someJSCode/__placeholder__.js 
```

Is there a way to specify the `nodePath` for the `prettier-eslint` integration as per https://github.com/prettier/prettier-eslint#eslintconfig-object? Is there a better/easier way to do that?

Thanks

**Comment by chemzqm** [comment]
> I usually open neovim from the root to have all the folders available and work on different languages, 

Its bad idea, many language server don't have support for multiple folders, so it's recommended to use different vim instance for different projects.

> Is there a way to specify the nodePath for the prettier-eslint integration as per 

No, it uses https://github.com/prettier/prettier-eslint#filepath-string instead of `eslintConfig`, eslint should find the config file for you.
