### ISSUE TITLE
[coc.nvim] error: { parser: "postcss" } is deprecated

### ISSUE THREAD

**Issue by sujiyuan** [neoclide/coc-prettier#20]
I encountered this error when I used the :Prettier command to format a css or less file:

[coc.nvim] error: { parser: "postcss" } is deprecated; we now treat it as { parser: "css" }.

**Comment by chemzqm** [comment]
You need fix your prettier config

**Comment by sujiyuan** [comment]
Thank you for replying to my question, maybe my understanding of the prettier is too little. I try to use:
npx prettier-stylelint --write -q 'src/**/*.{css,less}',

The result is perfect. So I think the possible reason is not that there is a problem with my configuration.

**Comment by chemzqm** [comment]
It uses prettier from your local dependencies or bundled prettier, not your $PATH, which could be a bit annoying.

**Comment by sujiyuan** [comment]
After I carefully looked at the reason why the prettier extention could not properly format the less file, I found that:

`src/errorHandler.ts`, line 50:
`if (cb instanceof Promise) {`
changed to
`if (Object.prototype.toString.call(cb) === '[object Promise]') {`

After that, formatting will work correctly.

**Comment by chemzqm** [comment]
They should be the same.
