### ISSUE TITLE
配置项里如何设置 支持 php 和 scss 或者其他格式的文件，像vim-prettier一样？

### ISSUE THREAD

**Issue by DemonCloud** [neoclide/coc-prettier#22]
vim-prettier 在选择的时候可以支持 其他的语言

https://github.com/prettier/vim-prettier

```vimL
Plug 'prettier/vim-prettier', {
  \ 'do': 'yarn install',
  \ 'branch': 'release/1.x',
  \ 'for': [
    \ 'javascript',
    \ 'typescript',
    \ 'css',
    \ 'less',
    \ 'scss',
    \ 'json',
    \ 'graphql',
    \ 'markdown',
    \ 'vue',
    \ 'lua',
    \ 'php',
    \ 'python',
    \ 'ruby',
    \ 'html',
    \ 'swift' ] }
```

但是这个插件我没有找到选项，
目前只支持 js，ts？

**Comment by fannheyward** [comment]
Prettier 支持的语言 coc-prettier 都支持，js/ts/css/json 等。如果要禁用某个语言，可以通过  `"prettier.disableLanguages": [ "" ]`设置。

**Comment by DemonCloud** [comment]
> Prettier 支持的语言 coc-prettier 都支持，js/ts/css/json 等。如果要禁用某个语言，可以通过 `"prettier.disableLanguages": [ "" ]`设置。

恩，收到了。 
只有js ts 支持局部选择pt，
其他语言智能全局format，谢谢回答
