### ISSUE TITLE
new version that includes disableSuccessMessage 

### ISSUE THREAD

**Issue by dzonatan** [neoclide/coc-prettier#23]
@chemzqm any plans for a new release that includes `prettier.disableSuccessMessage` config?

**Comment by chemzqm** [comment]
Consider send a PR.

**Comment by dzonatan** [comment]
What do you mean by PR? It's already implemented. https://github.com/neoclide/coc-prettier/commit/371936211faa9856d9dd252dfbde75e0e9e6573b
Only npm release is missing.

**Comment by chemzqm** [comment]
Oh, I forgot.
