### ISSUE TITLE
prettier.requireConfig is ignored if .editorconfig is present

### ISSUE THREAD

**Issue by jonasstenberg** [neoclide/coc-prettier#24]
When using 
```json
{
  "prettier.requireConfig": true
}
``` 
I assume that it will not format unless there is a [prettier configuration file](https://prettier.io/docs/en/configuration.html) present but it also thinks that `.editorconfig` is a valid config file.
Is this the expected behaviour?

Thanks!

**Comment by chemzqm** [comment]
Yes, https://github.com/neoclide/coc-prettier/blob/master/src/PrettierEditProvider.ts#L118 editorconfig is checked as well.
