### ISSUE TITLE
formatOnSave doesn't work for typescript.tsx

### ISSUE THREAD

**Issue by dylandjian** [neoclide/coc-prettier#27]
Hello! Thanks for the plugin !

It seems that the plugin doesn't work when using compound filetypes such as `typescript.tsx` (however it works when I manually set the filetype to `typescript` after opening the file).

Here is a simple config that makes it possible to reproduce :

![config](https://i.gyazo.com/a02436af50fe033227157e4f4d4f067a.png)

The filetype `typescript.tsx` is set by `vim-polyglot` which uses `yats.vim` : https://github.com/HerringtonDarkholme/yats.vim/blob/master/ftdetect/tsx.vim

Am I doing anything wrong ?
Thanks ! 😄

**Comment by dylandjian** [comment]
So after checking a bit more in depth, I found this issue : https://github.com/neoclide/coc-tsserver/issues/37 which seems very related to mine.
Indeed, when swapping to `typescriptreact` and putting it inside the `coc.preferences.formatOnSaveFiletypes` it works.

However, as the last comment suggests it breaks syntax highlighting since many of the highlighting plugins rely on `typescript.tsx` in order to apply both `typescript` and `tsx` syntax.

**Comment by chemzqm** [comment]
You don't need to change filetype, since coc.nvim will convert it, checkout `:h g:coc_filetype_map`

**Comment by dylandjian** [comment]
Oh ok I understand, thanks.

Maybe update the README to make it very clear that I need to have `typescriptreact` inside my coc-settings if I want it to work with the JSX / TSX filetypes ?

**Comment by kswope** [comment]
I'm not sure why I had to find this issue just to have to get coc-prettier to work with tsx.

The filetype is clearly typescript.tsx

![image](https://user-images.githubusercontent.com/321586/91669936-edba2b00-eae6-11ea-8d10-109bdf88f97b.png)

However only "typescriptreact" works in coc.preferences.formatOnSaveFiletypes

I have no idea what "typescriptreact" even is.

**Comment by chemzqm** [comment]
`typescriptreact` is used internally by coc.nvim, since VSCode use that and latest vim use `typescriptreact` too.
