### ISSUE TITLE
can't use prettier-plugin-svelte

### ISSUE THREAD

**Issue by makmm** [neoclide/coc-prettier#29]
`[coc.nvim] svelte not supported by prettier` :(

**Comment by chemzqm** [comment]
Your prettier's problem

**Comment by makmm** [comment]
no, it is supported by prettier. if i run `npx prettier [svelte file name]` it works, but coc.nvim doesn't think it is supported by prettier because i'm using a plugin to support it

**Comment by chemzqm** [comment]
It doesn't use command line for format, could be wrong prettier or it have to be explicit coded in extension to work. I'll not work on it, you can use command line to format your codr

**Comment by DanAndreasson** [comment]
I have a similar issue. Running `:CocCommand prettier.formatFile` produces `[coc.nvim] ruby not supported by prettier`.

I have `"prettier.onlyUseLocalVersion": true` in `coc-settings.json` and https://github.com/prettier/plugin-ruby installed. Running `./node_modules/.bin/prettier --write app/models/user.rb` does work as intended. 

Shouldn't `onlyUseLocalVersion` make it use the locally installed version?
