### ISSUE TITLE
Error: Cannot read property getSupportInfo of null - on coc-prettier startup

### ISSUE THREAD

**Issue by mhintz** [neoclide/coc-prettier#32]
On Vim startup, as coc-nvim initializes, I'm getting the following error:
![image](https://user-images.githubusercontent.com/2789742/66214087-10518300-e68f-11e9-8c35-c185683da190.png)

I'm using `vim-plug` to manage `coc-nvim` plugins. The error is happening in a project (my dotfiles) where I don't have a prettier config file, but I do have some random JSON files (like `coc-settings.json` 😄). I also don't have an `.eslintrc` or `.eslintignore` file in the project.

Interestingly, the error _doesn't_ happen on startup in a javascript project where there are `.eslintrc` and prettier config files.

Huge props for making such an amazing tool for Vim! I really love it and the plugin system is amazing and perfect.

Here's the output of `CocInfo`:
```
## versions

vim version: NVIM v0.3.8
node version: v12.9.1
coc.nvim version: 0.0.74
term: iTerm.app
platform: darwin

## Messages
coc.nvim initialized!
[coc.nvim] Error on active extension coc-prettier: TypeError: Cannot read property 'getSupportInfo' of null
## Output channel: watchman

[Info] watchman watching project: <project>
[Info] subscribing "**/.eslintr{c.js,c.yaml,c.yml,c,c.json}" in <project>
[Info] subscribing "**/.eslintignore" in <project>
[Info] subscribing "**/package.json" in <project>
```

**Comment by mhintz** [comment]
Oh wait, I read through some `coc-prettier` code and I think I know what's going on:

I don't have prettier installed globally, only locally in specific projects. So here, in the initialization code, it's not finding any installed version, and that's probably what's causing the prettier instance to be `null` https://github.com/neoclide/coc-prettier/blob/b82606312da9baa85f1ff5b601d6217f4b86b67f/src/utils.ts#L27

**Comment by chemzqm** [comment]
Can't reproduce.
