### ISSUE TITLE
Allow to configure where to read prettier binary?

### ISSUE THREAD

**Issue by jackysee** [neoclide/coc-prettier#36]
For a folder structure:
```
project
├── .git
├── server
│   ├── ...
├── client
│   ├── .pretteric.js
│   ├── package.json
│   ├── node_modules
│   │   ├── prettier
```

When open vim, coc's workspace folder would be set at `project`, so the local prettier binary cannot be resolved. It would be nice to have a way to configure exactly where to read the prettier binary.

**Comment by chemzqm** [comment]
You can configure workspaceFolder https://github.com/neoclide/coc.nvim/wiki/Using-workspaceFolders

**Comment by jackysee** [comment]
@chemzqm it seems that by current workspace folder resolving algorithm (up to down from cwd), it will always resolve to '.git' in the above example.

```
    "coc.preferences.rootPatterns": ["package.json", ".vim", ".git", ".hg"]
```
open `vim` at `project` (cwd), and then open file `client/src/someFile.js`, it will try:

- `project/package.json` --> not found
- `project/.vim` --> not found
- `project/.git` --> found! set as workspace folder

It will only work if the searching algorithm is in such order:

- `project/package.json` --> not found
- `project/client/package.json` --> found! set as workspace folder
