### ISSUE TITLE
coc-format-selected not working

### ISSUE THREAD

**Issue by jrock2004** [neoclide/coc-prettier#37]
I have the following in my init file `vmap <leader>f <Plug>(coc-format-selected)` but when I go into visual mode and select some stuff and hit the keymap, it changes my code but not correctly. I turned verbose logging on for eslint and I see the logs hit and it states that it should change it and the changes it requested it correct, but my file just does not update. Am I using this wrong?

**Comment by chemzqm** [comment]
No idea.

**Comment by revington** [comment]
Same for me with rust. I changed action to `coc-format` instead of `coc-format-selected` which formats the whole file but at least it works

**Comment by chemzqm** [comment]
Fixed on latest release branch of coc.nvim.
