### ISSUE TITLE
integrating a prettier plugin for ruby

### ISSUE THREAD

**Issue by arifb** [neoclide/coc-prettier#39]
Hi - great project. Wondering whether the scope of this project allows other prettier plugins to be integrated, specifically https://github.com/prettier/plugin-ruby?

Happy to contribute if this is outside the current functionality.

**Comment by fannheyward** [comment]
`yarn add --dev prettier @prettier/plugin-ruby` to add ruby plugin, and `:CocCommand prettier.formatFile` works.

**Comment by arifb** [comment]
Thanks @fannheyward for the quick reply - I'm getting an error however:

```
2019-11-18T22:36:40.396 ERROR (pid:36231) [commands] - TypeError: Cannot read property 'split' of undefined
    at addFilePath (/Users/arif/.local/share/nvim/plugged/coc-prettier/lib/index.js:5382:23)
    at Object.safeExecution (/Users/arif/.local/share/nvim/plugged/coc-prettier/lib/index.js:5431:21)
    at Object.<anonymous> (/Users/arif/.local/share/nvim/plugged/coc-prettier/lib/index.js:6470:31)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/arif/.local/share/nvim/plugged/coc-prettier/lib/index.js:301:58)
```

Any thoughts?

**Comment by fannheyward** [comment]
Can't reproduce. Can you run prettier in command line? something like this `./node_modules/.bin/prettier --write '**/*.rb'`, the error you got is came from https://github.com/neoclide/coc-prettier/blob/master/src/PrettierEditProvider.ts#L273 , cot-prettier run prettier format but failed.

**Comment by arifb** [comment]
Thanks for your quick replies @fannheyward . Was a result of the project having a .ruby-version file that pointed to a version of ruby that only existed in the VM where the project ran in, and me running nvim on my host. Matched up the rubies, and it runs fine :)

**Comment by jikkujose** [comment]
I am having issue with this. I am unable to get `coc-prettier` work for ruby files. Tried to add `yarn add --dev prettier @prettier/plugin-ruby` but that didn't work, think thats because I didn't have/need a package.json file.

Anyway to make this work for all Ruby files without having to put a package.json in the root?
