### ISSUE TITLE
Vue parser not available

### ISSUE THREAD

**Issue by reisnobre** [neoclide/coc-prettier#4]
Prettier added my other valid parsers.
I'm looking to use the vue parser 
```shell
"vue" (same parser as "html", but also formats vue-specific syntax) First available in 1.10.0
```
Is this available here?

**Comment by chemzqm** [comment]
You need make some configuration to make it work with vue https://github.com/neoclide/coc-prettier#prettierdisablelanguages-default-vue

**Comment by DanAndreasson** [comment]
@reisnobre does it work as of #31?

**Comment by uponeson** [comment]
@chemzqm Does the coc-vetur include prettier by default, hence its disabled in coc-prettier?

**Comment by chemzqm** [comment]
Yes

**Comment by chemzqm** [comment]
Yes
