### ISSUE TITLE
[Bug] Prettier-eslint takes presidence

### ISSUE THREAD

**Issue by kozer** [neoclide/coc-prettier#45]
I have a elsintrc config in my project but although I have some rules I don't want them to apply automatically when save, but only prettier to kicks in.

**Comment by chemzqm** [comment]
It should be caused by your other vim plugin.

**Comment by kozer** [comment]
I just disabled everything, clean my init.vim file, left only coc-prettier an try again. Same results. The problem is with react-exhaustive eslint rule. If I disable it, problem disappears.
I also run :CocCommand workspace.showoutput to check if there is anything running except prettier.
None. Is this something that has to do with prettier itself?

**Comment by kozer** [comment]
Intrestingly enough if I run `npm install --save-dev eslint-config-prettier` then the problem goes away
