### ISSUE TITLE
Error when trying to format css file.

### ISSUE THREAD

**Issue by thepenguinthatwants** [neoclide/coc-prettier#60]
Hi!

I installed coc-prettier and added

`  "coc.preferences.formatOnSaveFiletypes": ["css", "Markdown", "python"],`

When I save a css file I get.

```
[coc.nvim] Formatted by prettier
[coc.nvim] error: UnhandledRejection: No configuration provided for /home/mike/test.css
Error: No configuration provided for /home/,ole/testi.css
    at module.exports (/home/mike/.config/coc/extensions/node_modules/coc-prettier/node_modules/stylelint/lib/utils/configurationError.js:8:28)
```

Any clue why it gives such error?

**Comment by chemzqm** [comment]
Can't reproduce

**Comment by chemzqm** [comment]
Looks you have prettier.stylelintIntegration to true but didn't provide stylelint configuration.
