### ISSUE TITLE
Cannot find module 'core-js/modules/es.array.iterator'

### ISSUE THREAD

**Issue by leanbalma** [neoclide/coc-prettier#63]
I don't know if it's just me, but after updating to `v1.1.14`, running `:Format` gives me this error and the file is not formatted:

```
## Output channel: prettier

[Error - 5/27/2020, 12:15:04 PM:] Cannot find module 'core-js/modules/es.array.iterator'
```

I fixed it by installing `core-js`, but I'm not sure if that's the proper solution (I noticed it was removed in the [latest commit](https://github.com/neoclide/coc-prettier/commit/cb72171e112313bd58545ebecdc390a3b2647a3b#diff-8ee2343978836a779dc9f8d6b794c3b2L1086), since it's not a `prettier-eslint` requirement anymore). If it is, I'd be happy to send a PR.

**Comment by OkanEsen** [comment]
This must be an issue of prettier-eslint: https://github.com/prettier/prettier-eslint/issues/348.

I installed a previous version of coc-prettier until the aforementioned issue gets fixed.

**Comment by bapjiws** [comment]
> I installed a previous version of coc-prettier
@OkanEsen how did you manage to do it? I can't seem to find it in the docs :)

**Comment by dmitmel** [comment]
@bapjiws `:CocInstall coc-prettier@1.1.12`

**Comment by OkanEsen** [comment]
In addition what @dmitmel said, I also locked the version so it doesn't get overwritten via auto update.

Steps: 
1. `:CocList extensions`
2.  Navigate to `coc-prettier` or search by typing
3. Press `Tab` and then `l` for lock

Same steps for unlocking as soon as the bug gets fixed.

PS: I also installed the version `1.1.13`, which shouldn't make any difference tho.

**Comment by fabiomcosta** [comment]
Oh boy, this is finally "fixed" (well at least the file is formatted), thx @dmitmel and @OkanEsen !
