### ISSUE TITLE
Formatting Java

### ISSUE THREAD

**Issue by abenz1267** [neoclide/coc-prettier#64]
Hi,

is it possible to use coc-prettier to format Java files? There is https://github.com/jhipster/prettier-java that let's me format via command-line, but i was wondering if coc-prettier could handle it as well in order to format on save.

Right now when trying `:CocCommand prettier.formatFile` I get `Command error: cannot read property 'replace' of undefined`.

Any solution?

CocInfo:
```
## versions

vim version: NVIM v0.4.3
node version: v14.3.0
coc.nvim version: 0.0.78-0c973a7a47
coc.nivm directory: /home/andrej/.config/nvim/bundle/coc.nvim
term: xterm-256color
platform: linux

## Output channel: prettier


## Output channel: snippets

[Info 6:37:54 PM] Using ultisnips directories: UltiSnips /home/andrej/.config/coc/ultisnips
[Info 6:37:54 PM] Using ultisnips python command: pyx

## Output channel: java

[Info  - 6:38:01 PM] JDT Language Server started
[object Object]
```

Regards

**Comment by leanbalma** [comment]
You'd need to use another code formatter. Prettier supports just the languages mentioned here: https://prettier.io/docs/en/index.html

**Comment by abenz1267** [comment]
Please read my post before answering.

I literally linked the plugin that let's you format Java files with Prettier.

**Comment by chemzqm** [comment]
Can't make it for now since it check supported languageIds from prettier

**Comment by abenz1267** [comment]
I see. Thanks for the answer!

Regards
