### ISSUE TITLE
success message outputed but nothing happens

### ISSUE THREAD

**Issue by GopherJ** [neoclide/coc-prettier#69]
I'm trying different coc plugins to just finish my personal config at: https://github.com/GopherJ/cfg/blob/master/coc/.vimrc

So really sorry I create some different issues when things are unexpected~

My problem while using coc-prettier includes:

1. #68  it doesn't use global config, which makes it hard to use for different projects, some projects dont even have prettier config, I need to copy one which isn't ideal.

2. seems a bug? It shows formatted but nothing happens.

I created a file: `test.js` with the following content:

```js
        let c = 1;
```

while saving it, it gives me:

```
coc.nvim... formatted
```

but nothing has changed.

vim version: `8.2`
coc prettier config:

```
        "prettier.singleQuote": false,
        "prettier.trailingComma": "es5",
        "prettier.tabWidth": 4,
        "prettier.semi": true,
        "prettier.useTabs": true,
        "prettier.bracketSpacing": true,
        "prettier.disableLanguages": ["vue"],
        "prettier.eslintIntegration": true
```

**Comment by GopherJ** [comment]
It does work for multiple lines but not for only one line.

**Comment by chemzqm** [comment]
I can't reproduce.

**Comment by GopherJ** [comment]
@chemzqm I upgraded but it dosen't work

**Comment by GopherJ** [comment]
@chemzqm `:CocInstall coc-prettier@1.1.12` this worked as suggested in #63
