### ISSUE TITLE
RFC: what do you think about using prettier_d approach for coc-prettier?

### ISSUE THREAD

**Issue by sandangel** [neoclide/coc-prettier#7]
[prettier_d](https://github.com/josephfrazier/prettier_d)
hi @chemzqm 
Basically, it spins up a server to reduce prettier startup time => faster formatting time

**Comment by chemzqm** [comment]
coc-prettier runs in nodejs process of coc.nvim, it doesn't have overhead of node startup and module load, so I don't think that could be useful.
