### ISSUE TITLE
Can't format with prettier twig-melody plugin

### ISSUE THREAD

**Issue by Isos9** [neoclide/coc-prettier#71]
Hi,

I added this prettier [plugin](https://github.com/trivago/prettier-plugin-twig-melody) for html twig files, and installed a local prettier in my dev dependencies.

But when I try to format a "html.twig" file, here's the error I get : 

`
TypeError: Cannot read property 'replace' of undefined
    at /home/isos/.config/nvim/plugged/coc.nvim/build/index.js:32818:41
    at Array.forEach (<anonymous>)
    at Document.applyEdits (/home/isos/.config/nvim/plugged/coc.nvim/build/index.js:32817:15)
    at Object.<anonymous> (/home/isos/.config/coc/extensions/node_modules/coc-prettier/lib/index.js:229:32)
    at Generator.next (<anonymous>)
    at fulfilled (/home/isos/.config/coc/extensions/node_modules/coc-prettier/lib/index.js:115:58)
`

When I format with the local prettier in node_modules, it works, the local prettier doesn't seems to be used for this filetype. Is there something I'm missing ?

**Comment by Isos9** [comment]
I saw on one issues that it's because of the default supported languages, maybe a pull request which ignore the supported languages when a local prettier is installed would solve the problem ? @chemzqm  tell me if that kind of solution can work, I'll see if I can make it.

**Comment by ccchapman** [comment]
Any luck with this?

I also have issues getting `coc-prettier` to work with `prettier-plugin-twig-melody` even though `npx prettier --write` works as expected. It seems to have a conflict with something bundled with `coc-prettier`.

My `filetype` is `html.twig`. If I change the filetype to `twig`, `coc-prettier` will format it as I expect. I thought `prettier.onlyUseLocalVersion` could resolve the issue, but it did not help.

**Comment by chemzqm** [comment]
`:h g:coc_filetype_map`

**Comment by ccchapman** [comment]
Yes I already use file maps. `coc-prettier` must have extraneous formatting because of the HTML file type, which is undesirable when using with a Prettier extension for Twig. There should be a way to avoid this unexpected formatting.
