### ISSUE TITLE
Coc-prettier doesn't recognize vue filetype

### ISSUE THREAD

**Issue by eduardoarandah** [neoclide/coc-prettier#73]
![image](https://user-images.githubusercontent.com/4065733/86499505-35c00a00-bd51-11ea-912b-f28bdc066f85.png)

Auto formatting works with javascript and php but not vue. 

I tried manually setting filetype: 

`:set filetype=vue`

Any ideas why ?

**Comment by eduardoarandah** [comment]
It magically worked!
I'm not sure if it's because I added `coc-vetur`  plugin or the existence of `eslint-plugin-vue` in the project

anyway... leaving this here if it helps:

```
{
  "coc.preferences.formatOnType": true,
  "coc.preferences.formatOnSaveFiletypes": ["javascript", "php", "vue"],
  "prettier.eslintIntegration": true,
  "vetur.format.defaultFormatter.html": "prettier",
  "vetur.format.defaultFormatter.css": "prettier",
  "vetur.format.defaultFormatter.js": "prettier-eslint"
}
```

**Comment by npearson72** [comment]
It's probably working because you have `"pretier.eslintIntegration": true`

However, the problem is that this setting is deprecated by Prettier (https://github.com/prettier/prettier-vscode/issues/999) and it also throws an error in typescript (https://github.com/neoclide/coc-prettier/issues/62)

**Comment by euoia** [comment]
This appears to be because of this:
https://github.com/neoclide/coc-prettier#prettierdisablelanguages-default-vue

I wonder why Vue was set at the default?

**Comment by chemzqm** [comment]
It's copied from prettier-vscode.
