### ISSUE TITLE
:wq is slow when formatOnSaveFileTypes has been set

### ISSUE THREAD

**Issue by GopherJ** [neoclide/coc-prettier#74]
It tooks 1 to 2 seconds to exit vim for 300 lines typescript file. I think it's already pretty long which influence a lot user experience.

**Comment by GopherJ** [comment]
![image](https://user-images.githubusercontent.com/33961674/86574907-cc214500-bf76-11ea-82a9-4c13cc48b096.png)

**Comment by GopherJ** [comment]
Let's say the using the example of `coc-actions`'s code. 

https://github.com/iamcco/coc-actions/blob/master/src/actions.ts

It's 282 lines, when I exit vim using `:wq`, I need to wait a bit

**Comment by GopherJ** [comment]
close in favor of https://github.com/neoclide/coc.nvim/issues/2148

**Comment by tony** [comment]
I don't know if this is really resolved or not - I'm confused as to where this comes from or how to debug it.
