### ISSUE TITLE
endOfLine setting forced to be crlf / cr

### ISSUE THREAD

**Issue by ybbond** [neoclide/coc-prettier#77]
## Details

Everytime I saved in any file which extension included in `"coc.preferences.formatOnSaveFiletypes"`, extra new line will be created.

This happen in project that has prettier installed, or any file that has extension that will be auto formatted on save.

## Further Information

- vim version: **NVIM v0.4.3**
- node version: **v12.18.2**
- coc.nvim version: **0.0.78-6051c48732**
- coc-prettier: **v1.1.16**

<details>
<summary>coc-settings.json, prettier section</summary>

The setting for Coc (`:CocConfig`) that may be related to this issue.

```json
{
  "coc.preferences.formatOnSaveFiletypes": [
    "javascript",
    "javascriptreact",
    "typescript",
    "typescriptreact",
    "json",
    "reason",
    "reasonreact"
  ],
  "prettier.eslintIntegration": true,
  "prettier.tslintIntegration": true,
  "prettier.endOfLine": "lf",
  "prettier.ignorePath": ".prettierignore",
}
```
</details>

<details>
<summary>.eslintrc that contains prettier config</summary>

My project's `.eslintrc`, only part that is related to prettier.
```json
{
  "prettier/prettier": [
    "error",
    {
      "singleQuote": true,
      "trailingComma": "es5",
      "bracketSpacing": false,
      "jsxBracketSameLine": true,
      "printWidth": 80
    }
  ]
}
```
</details>

**Comment by chemzqm** [comment]
Fixed on latest release branch of coc.nvim.

**Comment by ybbond** [comment]
confirmed fix after running `:CocUpdate`. Thank you @chemzqm ! that was fast

I can close the vscode and continue working on nvim now :D

**Comment by tbremer** [comment]
Came to report this same issue, thanks for the fast fix!
