### ISSUE TITLE
eslintIntegration: true always formats the entire file

### ISSUE THREAD

**Issue by kyletruong** [neoclide/coc-prettier#78]
With `"prettier.eslintIntegration": true` whenever I run `coc-format-selected` my entire file is always formatted instead of my selected code.

My relevant neovim config:
```
xmap <leader>f <Plug>(coc-format-selected)
nmap <leader>f <Plug>(coc-format-selected)
```

I've read that this may be an issue with ESLint not supporting range selection, is this still true and is there anything I can do fix this problem?

**Comment by chemzqm** [comment]
Looks like issue of prettier.

**Comment by kyletruong** [comment]
Anything I can do to make prettier with eslint integration format only my selected range rather than the entire file?

**Comment by chemzqm** [comment]
Need fix for prettier, my recommendation is not only use prettier for format and eslint for diagnostics without format options.
