### ISSUE TITLE
Is there a way to make this work on PHP?

### ISSUE THREAD

**Issue by balapa** [neoclide/coc-prettier#79]

**Comment by aasutossh** [comment]
Not yet, I guess.

**Comment by euoia** [comment]
It works for me, in that you can run `:CocCommand prettier.formatFile` while editing a php buffer, and it will use Prettier to format the current file. But adding `php` to `coc.preferences.formatOnSaveFiletypes` in `coc-settings.json` is not working - my buffer is not formatted upon saving. I don't know why this is.

You can separately configure vim to run the current buffer through prettier using an autocmd:

```
autocmd BufWritePre *.php :CocCommand prettier.formatFile
```

**Comment by fannheyward** [comment]
> my buffer is not formatted upon saving

@euoia try increase `coc.preferences.willSaveHandlerTimeout` in your coc-settings.json, the default timeout is 500ms that some formatter maybe failed to run in time.

**Comment by ThomasTraineau** [comment]
I am getting this error `[coc.nvim] php not supported by prettier` when running `:CocCommand prettier.formatFile`

**Comment by chemzqm** [comment]
You have to use local prettier and make sure your prettier have support for php
