### ISSUE TITLE
prettier/plugin-pug

### ISSUE THREAD

**Issue by fredericobenevides** [neoclide/coc-prettier#80]
I'm trying to use coc-prettier with pug but it's not working.

my package.json has theses dependencies

<pre>
"@prettier/plugin-pug": "^1.4.4",
"prettier": "^2.0.5",
</pre>

I changed coc-settings.json to have:

<pre>
"prettier.onlyUseLocalVersion": true
</pre>

and ran the command inside a pug file

<pre>
:CocCommand prettier.formatFile
</pre>

and returned the error

<pre>
pug not supported by prettier
</pre>

**Comment by chemzqm** [comment]
It's expected since this plugin doesn't have support for set prettier plugins yet.

**Comment by chemzqm** [comment]
I won't take time to fix this for now, it would be appreciated if somebody want to help.

**Comment by ryeballar** [comment]
prettier/plugin-pug#151 should resolve this issue once it is published.

**Comment by chemzqm** [comment]
Make sure install prettier plugin with the prettier that coc-prettier is using.
