### ISSUE TITLE
Prettier isn't formatting .svelte files using my settings

### ISSUE THREAD

**Issue by nimainimaii** [neoclide/coc-prettier#82]
This is my coc  config file: 
```
{
    "eslint.filetypes": [
        "javascript",
        "javascriptreact",
        "typescript",
        "typescriptreact",
        "svelte"
    ],
    "coc.preferences.formatOnSaveFiletypes": [
        "javascript",
        "javascriptreact",
        "typescript",
        "typescriptreact",
        "svelte"
    ],
    "prettier.tabWidth": 4,
    "prettier.arrowParens": "avoid",
    "prettier.printWidth": 120,
    "prettier.semi": false,
    "clangd.path": "/home/nimai/.config/coc/extensions/coc-clangd-data/install/10.0.0/clangd_10.0.0/bin/clangd",
    "eslint.nodePath": "/home/nimai/.nvm/versions/node/v12.18.2/bin/node"
}
```
Format on save works fine for JSX/TSX and vanilla JavaScript/TypeScript files:
![jsx](https://user-images.githubusercontent.com/53116839/88263624-f3eb0980-cce7-11ea-9acd-199f320eb4f3.png)

...but it doesn't use my settings for svelte files:
![svelte](https://user-images.githubusercontent.com/53116839/88263689-10874180-cce8-11ea-99cd-9c79f3703a95.png)

As you can see, it's using a tab width of 2 and adding semi-colons. What am I doing wrong?

**Comment by chemzqm** [comment]
The bundled prettier doesn't have support for svelte
