### ISSUE TITLE
coc-prettier is causing cursor jumping.

### ISSUE THREAD

**Issue by Annis-Monadjem** [neoclide/coc-prettier#91]
coc-prettier version 1.1.17 on saving JS files causes cursor to jump to by few lines up to beginning of buffer.

After removing/uninstalling coc-prettier the problem went away.

**Comment by chemzqm** [comment]
Can't reproduce.

**Comment by Annis-Monadjem** [comment]
To reproduce i faithfully follow both https://github.com/neoclide/coc-prettier and https://prettier.io/docs/en/vim.html for installing prettier in Vim/Neovim:

1) Neovim: CocInstall coc-prettier<Enter>

2) Insert into init.vim:
Plug 'neoclide/coc.nvim', {'branch': 'release'}
command! -nargs=0 Prettier :call CocAction('runCommand', 'prettier.formatFile')

3) Insert into coc-settings.json:
{
  "coc.preferences.formatOnSaveFiletypes": [
    "javascript",
    "javascriptreact",
    "typescript",
    "typescriptreact",
    "css",
    "markdown",
    "json",
  ],
}

3) Execute:
a) Neovim: source $MYVIMRC<Enter>
b) Neovim: PlugInstall<Enter>
c) Neovim: PlugUpdate<Enter>
d) Neovim: UpdateRemotePlugins<Enter>
e) Neovim: Coc-Rebuild<Enter>
f) Neovim: Coc-Restart<Enter>
g) Neovim: Coc-Update<Enter>

4) Restart Neovim:
a) Neovim: w!
b) **Observation**: After saving the buffer each time the cursor moves by 2 lines up.

5) Reverse the Problem described in #4):
a) Neovim: ~/.config/coc/extensions/package.json>Remove coc-prettier from within package.json file.
b) bash> rm -rf ~/.config/coc/extensions/node_modules/coc-prettier
c) Neovim: CocUninstall coc-prettier
d) **Observation**: After saving the buffer the cursor remains fixed in same position in buffer.

**Comment by Annis-Monadjem** [comment]
Reproduction of coc-prettier cursor jumping problem.

**Comment by Annis-Monadjem** [comment]
Reproduction of coc-prettier cursor jumping problem.
