### ISSUE TITLE
coc-prettier causes cursor to jump in Neovim

### ISSUE THREAD

**Issue by Annis-Monadjem** [neoclide/coc-prettier#92]
**Problem**: coc-prettier version 1.1.17 on saving JS files causes cursor to annoyingly jump to by 2 lines up.

**Reproduction**:
To reproduce i faithfully follow both https://github.com/neoclide/coc-prettier and https://prettier.io/docs/en/vim.html manuals to install prettier in Vim/Neovim:

1) Install coc-prettier:
  a) Neovim: CocInstall coc-prettier<Enter>

2) Insert into init.vim:
  a) Plug 'neoclide/coc.nvim', {'branch': 'release'}
  b) command! -nargs=0 Prettier :call CocAction('runCommand', 'prettier.formatFile')

3) Insert into coc-settings.json:
{
  "coc.preferences.formatOnSaveFiletypes": [
    "javascript",
    "javascriptreact",
    "typescript",
    "typescriptreact",
    "css",
    "markdown",
    "json",
  ],
}

4) Execute:
  a) Neovim: source $MYVIMRC<Enter>
  b) Neovim: PlugInstall<Enter>
  c) Neovim: PlugUpdate<Enter>
  d) Neovim: UpdateRemotePlugins<Enter>
  e) Neovim: Coc-Rebuild<Enter>
  f) Neovim: Coc-Restart<Enter>
  g) Neovim: Coc-Update<Enter>

5) Restart Neovim:
  a) Neovim: w!<Enter>
  b) Neovim: checkhealth<Enter>            (OK on all tests)
  **Observation**: After saving the buffer each time the cursor moves by 2 lines up.

6) Reverse the Problem described in #4):
  a) Neovim: ~/.config/coc/extensions/package.json>Remove coc-prettier from within package.json file.
  b) bash> rm -rf ~/.config/coc/extensions/node_modules/coc-prettier<Enter>
  c) Neovim: CocUninstall coc-prettier<Enter>
  **Observation**: After saving the buffer the cursor remains fixed in same position in buffer.

Let me know if the above helps.

**Comment by chemzqm** [comment]
Can't reproduce, try minimal vimrc and debug coc.nvim https://github.com/neoclide/coc.nvim/wiki/Debug-coc.nvim
