### ISSUE TITLE
Add eslintPath option for eslint_d support in coc-prettier

### ISSUE THREAD

**Issue by utrumo** [neoclide/coc-prettier#93]
I really need the ability to specify eslint_d as an eslint executable. It works much faster, and cli commands are fully compatible and exactly the same as the original eslint. Only the executable name differs. Where eslint check takes 10 seconds, eslint_d manages in 2 seconds - due to clever caching of the results of the previous check. This is vital with plugins such as eslint-plugin-import because of which check is carried out for a very long time.

Can you add eslint path to executable option?

**Comment by chemzqm** [comment]
It's not possible since this extension use prettier module
