### ISSUE TITLE
Peer dependency bug found in coc-vetur and coc-tsserver still exists here

### ISSUE THREAD

**Issue by NICHTJ3** [neoclide/coc-prettier#95]
A similar issue to the one talked about here https://github.com/neoclide/coc-vetur/issues/54 still exists in this plugin

**Comment by chemzqm** [comment]
My suggestion is add `  "npm.binPath": "/path/to/yarn",` to your coc-settings.json

**Comment by NICHTJ3** [comment]
I will do that. I believe the issue for this plugin is also related to prettier-tslint's peer dependency on an older version of prettier so it seems to be out of your hands if you wanted to continue supporting tslint as that package appears to no-longer be maintained.

**Comment by chemzqm** [comment]
It's npm's upgrade that breaks everything.

**Comment by NICHTJ3** [comment]
Yeah but it's only cause it resolves the peer dependencies automatically
