### ISSUE TITLE
[question] 如何让 Vue 使用 ESLint 来格式化

### ISSUE THREAD

**Issue by SLin0218** [neoclide/coc-prettier#97]
请问能配置 `ESLint` 来格式化 `Vue`。目前只能在 `javaScript` 使用。
`vue` 使用和会 加上 `;` 并且转换为双引号。

**Comment by chemzqm** [comment]
取决于你用的工具，无法解答

**Comment by SLin0218** [comment]
`prettier.eslintIntegration` (default: false) - JavaScript and TypeScript only 
配置了此项，但只支持 无法支持 `vue`  文件。
